packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@nestjs/core': false
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: false
  esbuild: false
  prisma: true
  simple-git-hooks: false
