packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  simple-git-hooks: false
